//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Runbook) DeepCopyInto(out *Runbook) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Runbook.
func (in *Runbook) DeepCopy() *Runbook {
	if in == nil {
		return nil
	}
	out := new(Runbook)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Runbook) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RunbookList) DeepCopyInto(out *RunbookList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Runbook, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RunbookList.
func (in *RunbookList) DeepCopy() *RunbookList {
	if in == nil {
		return nil
	}
	out := new(RunbookList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RunbookList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RunbookSpec) DeepCopyInto(out *RunbookSpec) {
	*out = *in
	out.ReconcileInterval = in.ReconcileInterval
	out.GracePeriodLastRun = in.GracePeriodLastRun
	if in.FailedJobsHistoryLimit != nil {
		in, out := &in.FailedJobsHistoryLimit, &out.FailedJobsHistoryLimit
		*out = new(int32)
		**out = **in
	}
	if in.SuccessfulJobsHistoryLimit != nil {
		in, out := &in.SuccessfulJobsHistoryLimit, &out.SuccessfulJobsHistoryLimit
		*out = new(int32)
		**out = **in
	}
	if in.Matchers != nil {
		in, out := &in.Matchers, &out.Matchers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Suspend != nil {
		in, out := &in.Suspend, &out.Suspend
		*out = new(bool)
		**out = **in
	}
	in.Template.DeepCopyInto(&out.Template)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RunbookSpec.
func (in *RunbookSpec) DeepCopy() *RunbookSpec {
	if in == nil {
		return nil
	}
	out := new(RunbookSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RunbookStatus) DeepCopyInto(out *RunbookStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.FiringAlerts != nil {
		in, out := &in.FiringAlerts, &out.FiringAlerts
		*out = make([]RunbookStatusFiringAlert, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.FiringAlertsCount != nil {
		in, out := &in.FiringAlertsCount, &out.FiringAlertsCount
		*out = new(int32)
		**out = **in
	}
	if in.RunningJobs != nil {
		in, out := &in.RunningJobs, &out.RunningJobs
		*out = make([]RunbookStatusRunningJob, len(*in))
		copy(*out, *in)
	}
	if in.RunningJobsCount != nil {
		in, out := &in.RunningJobsCount, &out.RunningJobsCount
		*out = new(int32)
		**out = **in
	}
	if in.FailedJobsCount != nil {
		in, out := &in.FailedJobsCount, &out.FailedJobsCount
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RunbookStatus.
func (in *RunbookStatus) DeepCopy() *RunbookStatus {
	if in == nil {
		return nil
	}
	out := new(RunbookStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RunbookStatusFiringAlert) DeepCopyInto(out *RunbookStatusFiringAlert) {
	*out = *in
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RunbookStatusFiringAlert.
func (in *RunbookStatusFiringAlert) DeepCopy() *RunbookStatusFiringAlert {
	if in == nil {
		return nil
	}
	out := new(RunbookStatusFiringAlert)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RunbookStatusRunningJob) DeepCopyInto(out *RunbookStatusRunningJob) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RunbookStatusRunningJob.
func (in *RunbookStatusRunningJob) DeepCopy() *RunbookStatusRunningJob {
	if in == nil {
		return nil
	}
	out := new(RunbookStatusRunningJob)
	in.DeepCopyInto(out)
	return out
}
